import "~/styles/globals.css";

import { type Metadata } from "next";
import { JetBrains_Mono, Space_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const JBMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-family",
})
const SpaceMono = Space_Mono({
  subsets: ["latin"],
  variable: "--space-mono",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`bg-(--background0) ${JBMono.variable} ${SpaceMono.variable}`}>
      <body>
        <header className="w-full flex flex-col">
          <div className="flex flex-col" box-="round" shear-="top">
            <div className="header flex px-[1ch]">
              <h1 className="text-(--primary1) bg-(--background0)">Noti Page</h1>
            </div>
            <span className="px-[1ch] py-0 sm:py-[1lh] flex flex-col sm:flex-row place-items-start gap-0 sm:gap-[1ch]">
              <h1>Accounting</h1>
              <h1 className="hidden sm:block">|</h1>
              <h1>Daily Affairs</h1>
              <h1 className="hidden sm:block">|</h1>
              <h1>Profile</h1>
            </span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
